prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'namespace-monitoring'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - monitoring
      - job_name: 'fluentbit'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - fluentbit