apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: loki
  namespace: fluentbit
  labels:
    fluentbit.fluent.io/enabled: "true"
spec:
  match: "*"
  loki:
    host: loki.monitoring.svc.cluster.local
    port: 3100
---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: tail
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  tail:
    tag: kube.*
    path: "/var/log/containers/*.log"
    readFromHead: true
    parser: docker
    multilineParser: "docker, cri"
    refreshIntervalSeconds: 10
    memBufLimit: 5MB
    bufferMaxSize: "50MB"
    bufferChunkSize: "1MB"
    skipLongLines: true
    db: /fluent-bit/tail/pos.db
    dbSync: Normal
    storageType: "filesystem"
    pauseOnChunksOverlimit: "true"

---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: systemd
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  systemd:
    tag: host.*
    systemdFilter: "_SYSTEMD_UNIT=kubelet.service"
    readFromTail: true
