apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: tail
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  tail:
    tag: kube.*
    path: "/var/log/containers/*.log"
    readFromHead: true
    parser: docker
    multilineParser: "docker, cri"
    refreshIntervalSeconds: 10
    memBufLimit: 5MB
    bufferMaxSize: "50MB"
    bufferChunkSize: "1MB"
    skipLongLines: True
    db: /fluent-bit/tail/pos.db
    dbSync: Normal
    storageType: "filesystem"
    pauseOnChunksOverlimit: "on"