apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: loki
  namespace: fluentbit
  labels:
    fluentbit.fluent.io/enabled: "true"
spec:
  match: "*"
  loki:
    host: loki.monitoring.svc.cluster.local
    port: 3100
    labels: 
      - job=fluent-bit
      - namespace=$kubernetes_namespace_name
      - pod=$kubernetes_pod_name
      - container=$kubernetes_container_name